export const SpreadsheetConfig = Object.freeze({
  GRID_SIZE: 9,
  ROW_HEADER_CELL_OFFSET: 1,
  COLUMN_LABEL_BASE_CODE: 65,
  CSV_FILENAME: 'spreadsheet.csv',
  UTF8_BOM: '\uFEFF',
  CSV_MIME_TYPE: 'text/csv;charset=utf-8;',
  CSV_ROW_DELIMITER: '\r\n',
  CSV_FIELD_DELIMITER: ',',
  CSV_QUOTE_ESCAPE_PATTERN: /[",\r\n]/,
  STORAGE_KEY: 'spreadsheet-sheet-state',
  STORAGE_DEBOUNCE_MS: 300,
  SELECTORS: Object.freeze({
    GRID: '#sheet-grid',
    NAME_BOX: '#name-box-display',
    FORMULA_INPUT: '#formula-input',
    EXPORT_BUTTON: '#btn-export',
    CELL_INPUT: '#cell-input',
  }),
  CLASSES: Object.freeze({
    CELL: 'sheet-grid__cell',
    CELL_ACTIVE: 'active-cell',
    CELL_EDITING: 'editing-cell',
    CELL_DISPLAY: 'sheet-grid__cell-display',
    CELL_EXPANDED: 'sheet-grid__cell--expanded',
    CELL_DISPLAY_EXPANDED: 'sheet-grid__cell-display--expanded',
    COLUMN_HEADER: 'sheet-grid__col-header',
    COLUMN_HEADER_ACTIVE: 'sheet-grid__col-header--is-active',
    ROW_HEADER: 'sheet-grid__row-header',
    ROW_HEADER_ACTIVE: 'sheet-grid__row-header--is-active',
    CORNER: 'sheet-grid__corner',
  }),
  ARIA: Object.freeze({
    GRID_LABEL: '9 by 9 스프레드시트',
    SELECTED_FALSE: 'false',
    SELECTED_TRUE: 'true',
  }),
  TAB_INDEX: Object.freeze({
    INACTIVE: '-1',
    ACTIVE: '0',
  }),
});
